ITW/ITW/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

ITW/app/urls.py
from django.contrib import admin
from django.urls import path
from app import views

# Template urls
app_name = 'app'

urlpatterns = [
   path('register/', views.register, name='register'),
   path('', views.base, name='base'),
   path('login/', views.user_login, name='login'),
   path('ycalendar/', views.ycalendar, name='ycalendar'),
   path('logout/', views.user_logout, name='logout'),
   path('event/', views.create_event, name='event'),
   path('home/', views.CalanderView1, name='calendar'),
   path('event_detail/<int:event_id>/', views.event_details, name='event_detail'),
]

ITW/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # addition
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)

    def __str__(self):
        return self.user.username

class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('app:event_detail', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

ITW/app/forms.py
from django import forms
from .models import UserProfileInfo, Event
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(required=True, label='Email', widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(max_length=20, label='Username', widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserProfileInfo
        fields = ('gender',)

class EventForm(forms.ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': forms.DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': forms.DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    exclude = ['user']

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

ITW/app/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileForm, EventForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from datetime import datetime, timedelta, date
from django.utils.safestring import mark_safe
from calendar import HTMLCalendar
from django.views import generic
import calendar
from django.contrib.auth.models import User
from .utils import Calendar
from .models import Event

def base(request):
    return render(request, 'base.html', {})

def home(request):
    return render(request, 'home.html', {})

def register(request):
    registered = False
    if request.method == 'POST':
         user_form = UserForm(data=request.POST)
         profile_form = UserProfileForm(data=request.POST)
         if user_form.is_valid() and profile_form.is_valid():
             user = user_form.save()
             user.set_password(user.password)
             user.save()
             profile = profile_form.save(commit=False)
             profile.user = user
             profile.save()
             return HttpResponseRedirect(reverse('app:login'))
         else:
             print(user_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'register.html', {'user_form': user_form,
                                             'profile_form': profile_form,})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('app:calendar'))
            else:
                return HttpResponse("Account not active")
        else:
            context = {
                'message': "Username and Password are incorrect"
            }
            return render(request, "login.html", context)
    else:
        return render(request,'login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('app:base'))


def ycalendar(request):
    return render(request,'ycalendar.html',{})

def create_event(request):
    form = EventForm(request.POST or None)
    if request.POST and form.is_valid():
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        start_time = form.cleaned_data['start_time']
        end_time = form.cleaned_data['end_time']
        Event.objects.get_or_create(
            user=request.user,
            title=title,
            description=description,
            start_time=start_time,
            end_time=end_time
        )
        return HttpResponseRedirect(reverse('app:calendar'))
    return render(request, 'event.html', {'form': form})



def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def CalanderView1(request):
    d = get_date(request.GET.get('month', None))
    cal = Calendar(d.year, d.month)
    html_cal = cal.formatmonth(withyear=True)
    event_list = Event.objects.order_by('start_time')
    today = date.today()
    month = get_date(request.GET.get('month', None)).month

    return render(request, 'home.html', {'calendar': mark_safe(html_cal),
                                          'prev_month': prev_month(d),
                                          'next_month': next_month(d),
                                          'month':month,
                                          'today':today,
                                          'event':event_list})

def event_details(request, event_id):
    event = Event.objects.get(id=event_id)
    context = {
        'event': event,
    }
    return render(request, 'event_detail.html', context)

ITW/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  
  
  <title>
    {% block title %}
      Django Calendar
    {% endblock %}
  </title>
  

  {% block head %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  {% endblock %}
</head>



<body>
 <nav class="navbar navbar-expand-md navbar-dark bg-dark py-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'app:base' %}">
      <div class="navbar-first">
        Calendar
      </div>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:calendar' %}">Home</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:register' %}">Signup</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:ycalendar' %}">YearlyCalendar</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
       <span class="navbar-text">
          Welcome {{ user.get_username }}
      {% endif %}
      </span>
      </div>
      </div>
      </nav>
      {% block content %}
        <div id="welcometext">
          <h1>Welcome to</h1>
          <h2>Django-Calendar</h2>
        </div>
      {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="{% static '/script.js' %}" type="text/javascript"></script>
</body>
</html>

ITW/templates/event.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="#" style="
		margin-top: 5px;
		margin-left: 5px;
">
	<a class="btn btn-outline-dark" href="{% url 'app:calendar' %}"> Calendar </a>
</div>
<form method="post" class="event-form">
	{% csrf_token %}
	<table class="form form-table">
		{{ form|crispy }}
	</table><br>
	<tr><td colspan="2"><button type="submit" class="btn btn-outline-dark"> Submit </button></td></tr>
</form>
</center>
{% else %}
<div>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
	<symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
	</symbol>
	<symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
	</symbol>
	<symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
	</symbol>
</svg>
<center class="warning">
<div class="alert alert-danger d-flex align-items-center col-3" role="alert">
<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
<div>
	You have not logged in !
</div>
</div>
</div>
{% endif %}
{% endblock %}

ITW/templates/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="btn btn-outline-dark" href="{% url 'app:calendar' %}"> Calendar </a>
<div class="clearfix">
        <h1 class="display-4">Event Name: {{ event.title }}</h1><br>
        <p>From <span style="color: gray;">{{ event.start_time }}</span></p>
        <p> To <span style="color: gray;">{{ event.end_time }}</span></p>
        <hr>
        <p>{{ event.description }}</p>
    </div>
{% endblock %}

ITW/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Home Page
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="clearfix">
  <a class="btn btn-outline-dark left" href="{% url 'app:calendar' %}?{{ prev_month }}"> Previous Month </a>
  <form method="GET" class='year-month'>
   <input class="form-control" type="text" placeholder="Year-Month" name="month">
   <input type='submit' value="GO" class="btn btn-outline-dark right">
 </form>
  <a class="btn btn-outline-dark right new_event" href="{% url 'app:event' %}"> New Event </a>
  <a class="btn btn-outline-dark right next_month" href="{% url 'app:calendar' %}?{{ next_month }}"> Next Month </a>
 </div>
 <div class="calendar-event">
   <div class="event-viewbox">
     <table class="table table-hover">
    <thead>
      <tr>
        <h4 class="display-6">Upcoming Events</h4>
      </tr>
      <hr style="margin: 0;border-top: 1px solid black;opacity: 1;">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Time</th>
        <th scope="col">Title</th>        
      </tr>
    </thead>
    <tbody>
      {% for i in event %}
        {% if month == i.start_time.month %}
        {% if i.start_time.date >= today %}
        {% if i.user.username == user.get_username %}
      <tr>
        <td>{{ i.start_time.date }}</td>
        <td>{{ i.start_time.time }}</td>
        <td>{{ i.title }}</td>
      </tr>
       {% endif %}
       {% endif %}
       {% endif %}
      {% endfor %}
    </tbody>
  </table>
   </div>
  {{ calendar }}
 </div>
{% else %}
<div>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<center class="warning">
<div class="alert alert-danger d-flex align-items-center col-3" role="alert">
<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
<div>
  You have not logged in !
</div>
</div>
</center>
</div>
{% endif %}
{% endblock %}

ITW/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Login
{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'CSS/style.css' %}">
{% endblock %}

{% block content %}

<section id="cover" class="min-vh-100">
<div id="cover-caption">
 <div class="container">
  <div class="row text-white">
    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
      <h1 class="display-4 py-2 text-truncate" style="color: black">Log In</h1>
        <div class="px-2">
          <form action="{% url 'app:login' %}" class="justify-content-center", method="post">
            {% csrf_token %}
          <div class="form-group">
            <label class="sr-only" for='username'> Username: </label>
            <input type="text" name="username" class="form-control" placeholder="Enter Username">
          </div>
          <div class="form-group">
            <label class="sr-only" for='password'>Password: </label>
            <input type="password" name="password" class="form-control" placeholder="Password">
          </div>
          <br>
          <div style="color: rgb(185, 127, 0);font-size: small;">
            {{ message }} <br>
          </div>
          <br>
          <input class="btn btn-outline-dark" type="submit" value="Login">
        </form>
      </div>
    </div>
  </div>
 </div>
  </div>
</section>

{% endblock %}

ITW/templates/register.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Signup
{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'CSS/style.css' %}">
{% endblock %}

{% load crispy_forms_tags %}

<!DOCTYPE html>

  {% block content %}
  <br>
  <center>
    <h1 class="display-4"> Registration Form </h1>
  </center>
   <br>

  <form method="post" style="margin: 0px 500px 0px 500px; ">
      {% csrf_token %}
      {{ user_form|crispy }}
      {{ profile_form|crispy }} <br>
      <center>
        <input type="submit" class="btn btn-outline-dark" value="Submit">
      </center>
  </form>
  
  {% endblock %}

ITW/templates/ycalendar.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Calender</title>
        <link rel = "stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet"/> 


        <style>
        
        * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family:"Quicksand",sans-serif;

}

html{

    font-size: 62.5%;
}

.container   /*It changes the container settings you can assume it as the area behind the main calender the whole webpage*/
{
    width: 100%;
    height: 100vh;
    background-color: #12121f;
    color: #eee;
    display: flex;
    justify-content: center;
    align-items: center;
}

.calender{   /*It changes  the settings of the calender visible on the screen*/
    width: 45rem;
    height: 52rem;
    background-color: #222227;
    {% comment %} box-shadow: 0.5rem 3rem rgba(58, 15, 15, 0.1); /*IT creates the shadow of the box we have specified as calender you can remmove it later*/; {% endcomment %}
}

.month    /* It makes changes in the  month box specified  green in color*/
{
    width: 100%;
    height: 12rem;
    background-color: #167e56;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0 2rem;
    text-align: center;
    {% comment %} text-shadow: 0.3rem 0.5rem rgba(0,0,0,0.2); {% endcomment %}
}

.month i{  /*It changes the settings for the arrow buttons*/
    font-size: 2.5rem;  
    cursor: pointer;
}

.month h1{  /*It changes the month text settings i.e may fri ... in ths case we have written h1 because we have declared h1 under hte month class*/
    font-size: 3rem;
    font-weight: 400;
    text-transform: uppercase;
    letter-spacing: 0.2rem;
    margin-bottom: 1rem;
}

.month p{
    font-size: 1.6rem;
}

.month h2:hover{
    font-size: 2rem;
    background-color: #262626;
    border: 0.2rem solid #777;
    cursor:pointer;
}

.weekdays{
    width: 100%;
    height: 5rem;/*repressents the height of calender weekdays*/
    padding: 0rem 0.4rem 0rem 0.4rem; /*0 represents spacing from upper then LtoR then lower then RtoL*/
    display: flex;
    align-items: center;
}

.weekdays div  /*this will change the week days settings*/
{
   font-size: 1.5rem;/*it changes the font size of weekdays*/
   font-weight: 400; /*the weight changes the density of the words written*/
   letter-spacing: 0.2rem; /*it changes the spacing between the letters in the weekdays*/
   width: calc(43.6rem/7);
   display: flex;
   justify-content: center;
   align-items: center;
}

.days
{
  width:100%;
  display: flex;
  flex-wrap: wrap;
  padding: 0.2rem;

  
}

.days div
{
    font-size: 1.4rem;
    margin: 0.3rem;
    width: calc(40.4rem/7);
    height: 5rem;
    display: flex;
    justify-content:center;
    align-items: center;
    transition: background-color 0.2s;
}

.days div:hover:not(.today)
{
    background-color: #262626;
    border: 0.2rem solid #777;
    cursor:pointer;
}

.prev-date,
.next-date
{
  opacity: 0.5;

}


.today
{
    background-color: #167e56;
}




        
        
        </style>

    </head>
     <body>   
     <div class = "container"> <!--covers whole screen-->
       <div class = "calender"><!--covers the inner caender box-->>
           <div class = "month">
             <i class = "fas fa-angle-left
             prev" onclick="moveDate('prev')"></i>
             <div class="date">
                 <h1></h1>
                 <p></p>
                 <h2>AddEvent</h2>
             </div>
             <i class="fas fa-angle-right
             next" onclick="moveDate('next')"></i>
           </div>
           <div class="weekdays">
             <div>Sun</div>
             <div>Mon</div>
             <div>Tue</div>
             <div>Wed</div>
             <div>Thu</div>
             <div>Fri</div>
             <div>Sat</div>
           </div>
           <div class="days">
              

              
              
               
               
               
                

           </div>
       </div>
     </div>


        <script> 
        
        const date = new Date();

const renderCalendar = () => {
  date.setDate(1);

  const monthDays = document.querySelector(".days");

  const lastDay = new Date(
    date.getFullYear(),//gives current year
    date.getMonth() + 1,
    0
  ).getDate();

  const prevLastDay = new Date(
    date.getFullYear(),
    date.getMonth(),
    0
  ).getDate();

  const firstDayIndex = date.getDay();

  const lastDayIndex = new Date(
    date.getFullYear(),//current year
    date.getMonth() + 1,//current month
    0
  ).getDay();

  const nextDays = 7 - lastDayIndex - 1;

  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  document.querySelector(".date h1").innerHTML = months[date.getMonth()];

  document.querySelector(".date p").innerHTML = new Date().toDateString();

  let days = "";

  for (let x = firstDayIndex; x > 0; x--) {
    days += `<div class="prev-date">${prevLastDay - x + 1}</div>`;
  }

  for (let i = 1; i <= lastDay; i++) {
    if (
      i === new Date().getDate() &&
      date.getMonth() === new Date().getMonth()
    ) {
      days += `<div class="today">${i}</div>`;
    } else {
      days += `<div>${i}</div>`;
    }
  }

  for (let j = 1; j <= nextDays; j++) {
    days += `<div class="next-date">${j}</div>`;
    monthDays.innerHTML = days;
  }
};

document.querySelector(".prev").addEventListener("click", () => {
  date.setMonth(date.getMonth() - 1);
  renderCalendar();
});

document.querySelector(".next").addEventListener("click", () => {
  date.setMonth(date.getMonth() + 1);
  renderCalendar();
});

renderCalendar();

        
        </script>
       
    </body>
</html>